export const HARNESS_HEALTH_TIMEOUT_MS = 3_000;
export const HARNESS_MODELS_TIMEOUT_MS = 10_000;
export const HARNESS_RUN_TIMEOUT_MS = 10_000;
export const HARNESS_CHAT_TIMEOUT_MS = 10_000;
export const HARNESS_CONVERSATIONS_TIMEOUT_MS = 10_000;
export const HARNESS_SCHEDULER_TIMEOUT_MS = 5_000;
export const HARNESS_ENRICHMENT_TIMEOUT_MS = 10_000;
