/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PaRouteImport } from './routes/pa'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HubRouteImport } from './routes/hub'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as EnrichmentRouteImport } from './routes/enrichment'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulationsSimIdRouteImport } from './routes/simulations.$simId'
import { Route as ResearchIdRouteImport } from './routes/research_.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as HomeConnectorsRouteImport } from './routes/home.connectors'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as HubResearchIdRouteImport } from './routes/hub_.research.$id'
import { Route as AgentsEditIdRouteImport } from './routes/agents.edit.$id'
import { Route as AgentsIdRunsRunIdRouteImport } from './routes/agents.$id.runs.$runId'

const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PaRoute = PaRouteImport.update({
  id: '/pa',
  path: '/pa',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrichmentRoute = EnrichmentRouteImport.update({
  id: '/enrichment',
  path: '/enrichment',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsSimIdRoute = SimulationsSimIdRouteImport.update({
  id: '/$simId',
  path: '/$simId',
  getParentRoute: () => SimulationsRoute,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/research_/$id',
  path: '/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const HomeConnectorsRoute = HomeConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => HomeRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const HubResearchIdRoute = HubResearchIdRouteImport.update({
  id: '/hub_/research/$id',
  path: '/hub/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsEditIdRoute = AgentsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRunsRunIdRoute = AgentsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AgentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/enrichment': typeof EnrichmentRoute
  '/graph': typeof GraphRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRouteWithChildren
  '/hub': typeof HubRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/ops': typeof OpsRoute
  '/pa': typeof PaRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/research': typeof ResearchRoute
  '/setup': typeof SetupRoute
  '/simulations': typeof SimulationsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/home/connectors': typeof HomeConnectorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/simulations/$simId': typeof SimulationsSimIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/enrichment': typeof EnrichmentRoute
  '/graph': typeof GraphRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRouteWithChildren
  '/hub': typeof HubRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/ops': typeof OpsRoute
  '/pa': typeof PaRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/research': typeof ResearchRoute
  '/setup': typeof SetupRoute
  '/simulations': typeof SimulationsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/home/connectors': typeof HomeConnectorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/research/$id': typeof ResearchIdRoute
  '/simulations/$simId': typeof SimulationsSimIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/enrichment': typeof EnrichmentRoute
  '/graph': typeof GraphRoute
  '/harvest': typeof HarvestRoute
  '/home': typeof HomeRouteWithChildren
  '/hub': typeof HubRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/memory': typeof MemoryRoute
  '/ops': typeof OpsRoute
  '/pa': typeof PaRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/research': typeof ResearchRoute
  '/setup': typeof SetupRoute
  '/simulations': typeof SimulationsRouteWithChildren
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/home/connectors': typeof HomeConnectorsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/research_/$id': typeof ResearchIdRoute
  '/simulations/$simId': typeof SimulationsSimIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub_/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/enrichment'
    | '/graph'
    | '/harvest'
    | '/home'
    | '/hub'
    | '/live'
    | '/login'
    | '/logs'
    | '/memory'
    | '/ops'
    | '/pa'
    | '/projects'
    | '/research'
    | '/setup'
    | '/simulations'
    | '/agents/$id'
    | '/agents/new'
    | '/home/connectors'
    | '/projects/$id'
    | '/research/$id'
    | '/simulations/$simId'
    | '/agents/edit/$id'
    | '/hub/research/$id'
    | '/agents/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/enrichment'
    | '/graph'
    | '/harvest'
    | '/home'
    | '/hub'
    | '/live'
    | '/login'
    | '/logs'
    | '/memory'
    | '/ops'
    | '/pa'
    | '/projects'
    | '/research'
    | '/setup'
    | '/simulations'
    | '/agents/$id'
    | '/agents/new'
    | '/home/connectors'
    | '/projects/$id'
    | '/research/$id'
    | '/simulations/$simId'
    | '/agents/edit/$id'
    | '/hub/research/$id'
    | '/agents/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/enrichment'
    | '/graph'
    | '/harvest'
    | '/home'
    | '/hub'
    | '/live'
    | '/login'
    | '/logs'
    | '/memory'
    | '/ops'
    | '/pa'
    | '/projects'
    | '/research'
    | '/setup'
    | '/simulations'
    | '/agents/$id'
    | '/agents/new'
    | '/home/connectors'
    | '/projects/$id'
    | '/research_/$id'
    | '/simulations/$simId'
    | '/agents/edit/$id'
    | '/hub_/research/$id'
    | '/agents/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  ChatRoute: typeof ChatRoute
  CodeRoute: typeof CodeRoute
  EnrichmentRoute: typeof EnrichmentRoute
  GraphRoute: typeof GraphRoute
  HarvestRoute: typeof HarvestRoute
  HomeRoute: typeof HomeRouteWithChildren
  HubRoute: typeof HubRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MemoryRoute: typeof MemoryRoute
  OpsRoute: typeof OpsRoute
  PaRoute: typeof PaRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  SetupRoute: typeof SetupRoute
  SimulationsRoute: typeof SimulationsRouteWithChildren
  ResearchIdRoute: typeof ResearchIdRoute
  HubResearchIdRoute: typeof HubResearchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pa': {
      id: '/pa'
      path: '/pa'
      fullPath: '/pa'
      preLoaderRoute: typeof PaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrichment': {
      id: '/enrichment'
      path: '/enrichment'
      fullPath: '/enrichment'
      preLoaderRoute: typeof EnrichmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations/$simId': {
      id: '/simulations/$simId'
      path: '/$simId'
      fullPath: '/simulations/$simId'
      preLoaderRoute: typeof SimulationsSimIdRouteImport
      parentRoute: typeof SimulationsRoute
    }
    '/research_/$id': {
      id: '/research_/$id'
      path: '/research/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/home/connectors': {
      id: '/home/connectors'
      path: '/connectors'
      fullPath: '/home/connectors'
      preLoaderRoute: typeof HomeConnectorsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/hub_/research/$id': {
      id: '/hub_/research/$id'
      path: '/hub/research/$id'
      fullPath: '/hub/research/$id'
      preLoaderRoute: typeof HubResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/edit/$id': {
      id: '/agents/edit/$id'
      path: '/edit/$id'
      fullPath: '/agents/edit/$id'
      preLoaderRoute: typeof AgentsEditIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id/runs/$runId': {
      id: '/agents/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/agents/$id/runs/$runId'
      preLoaderRoute: typeof AgentsIdRunsRunIdRouteImport
      parentRoute: typeof AgentsIdRoute
    }
  }
}

interface AgentsIdRouteChildren {
  AgentsIdRunsRunIdRoute: typeof AgentsIdRunsRunIdRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdRunsRunIdRoute: AgentsIdRunsRunIdRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsEditIdRoute: typeof AgentsEditIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  AgentsEditIdRoute: AgentsEditIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface HomeRouteChildren {
  HomeConnectorsRoute: typeof HomeConnectorsRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeConnectorsRoute: HomeConnectorsRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SimulationsRouteChildren {
  SimulationsSimIdRoute: typeof SimulationsSimIdRoute
}

const SimulationsRouteChildren: SimulationsRouteChildren = {
  SimulationsSimIdRoute: SimulationsSimIdRoute,
}

const SimulationsRouteWithChildren = SimulationsRoute._addFileChildren(
  SimulationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  ChatRoute: ChatRoute,
  CodeRoute: CodeRoute,
  EnrichmentRoute: EnrichmentRoute,
  GraphRoute: GraphRoute,
  HarvestRoute: HarvestRoute,
  HomeRoute: HomeRouteWithChildren,
  HubRoute: HubRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MemoryRoute: MemoryRoute,
  OpsRoute: OpsRoute,
  PaRoute: PaRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResearchRoute: ResearchRoute,
  SetupRoute: SetupRoute,
  SimulationsRoute: SimulationsRouteWithChildren,
  ResearchIdRoute: ResearchIdRoute,
  HubResearchIdRoute: HubResearchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
