/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HubRouteImport } from './routes/hub'
import { Route as CodeRouteImport } from './routes/code'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIdRouteImport } from './routes/research.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as HubResearchIdRouteImport } from './routes/hub_.research.$id'
import { Route as AgentsEditIdRouteImport } from './routes/agents.edit.$id'
import { Route as AgentsIdRunsRunIdRouteImport } from './routes/agents.$id.runs.$runId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIdRoute = ResearchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResearchRoute,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const HubResearchIdRoute = HubResearchIdRouteImport.update({
  id: '/hub_/research/$id',
  path: '/hub/research/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsEditIdRoute = AgentsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRunsRunIdRoute = AgentsIdRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AgentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/research': typeof ResearchRouteWithChildren
  '/setup': typeof SetupRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/research/$id': typeof ResearchIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/research': typeof ResearchRouteWithChildren
  '/setup': typeof SetupRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/research/$id': typeof ResearchIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/chat': typeof ChatRoute
  '/code': typeof CodeRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/research': typeof ResearchRouteWithChildren
  '/setup': typeof SetupRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/research/$id': typeof ResearchIdRoute
  '/agents/edit/$id': typeof AgentsEditIdRoute
  '/hub_/research/$id': typeof HubResearchIdRoute
  '/agents/$id/runs/$runId': typeof AgentsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/hub'
    | '/login'
    | '/logs'
    | '/research'
    | '/setup'
    | '/agents/$id'
    | '/agents/new'
    | '/research/$id'
    | '/agents/edit/$id'
    | '/hub/research/$id'
    | '/agents/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/hub'
    | '/login'
    | '/logs'
    | '/research'
    | '/setup'
    | '/agents/$id'
    | '/agents/new'
    | '/research/$id'
    | '/agents/edit/$id'
    | '/hub/research/$id'
    | '/agents/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/architecture'
    | '/chat'
    | '/code'
    | '/hub'
    | '/login'
    | '/logs'
    | '/research'
    | '/setup'
    | '/agents/$id'
    | '/agents/new'
    | '/research/$id'
    | '/agents/edit/$id'
    | '/hub_/research/$id'
    | '/agents/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  ChatRoute: typeof ChatRoute
  CodeRoute: typeof CodeRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ResearchRoute: typeof ResearchRouteWithChildren
  SetupRoute: typeof SetupRoute
  HubResearchIdRoute: typeof HubResearchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$id': {
      id: '/research/$id'
      path: '/$id'
      fullPath: '/research/$id'
      preLoaderRoute: typeof ResearchIdRouteImport
      parentRoute: typeof ResearchRoute
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/hub_/research/$id': {
      id: '/hub_/research/$id'
      path: '/hub/research/$id'
      fullPath: '/hub/research/$id'
      preLoaderRoute: typeof HubResearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/edit/$id': {
      id: '/agents/edit/$id'
      path: '/edit/$id'
      fullPath: '/agents/edit/$id'
      preLoaderRoute: typeof AgentsEditIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id/runs/$runId': {
      id: '/agents/$id/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/agents/$id/runs/$runId'
      preLoaderRoute: typeof AgentsIdRunsRunIdRouteImport
      parentRoute: typeof AgentsIdRoute
    }
  }
}

interface AgentsIdRouteChildren {
  AgentsIdRunsRunIdRoute: typeof AgentsIdRunsRunIdRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdRunsRunIdRoute: AgentsIdRunsRunIdRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  AgentsEditIdRoute: typeof AgentsEditIdRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  AgentsEditIdRoute: AgentsEditIdRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface ResearchRouteChildren {
  ResearchIdRoute: typeof ResearchIdRoute
}

const ResearchRouteChildren: ResearchRouteChildren = {
  ResearchIdRoute: ResearchIdRoute,
}

const ResearchRouteWithChildren = ResearchRoute._addFileChildren(
  ResearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  ChatRoute: ChatRoute,
  CodeRoute: CodeRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ResearchRoute: ResearchRouteWithChildren,
  SetupRoute: SetupRoute,
  HubResearchIdRoute: HubResearchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
